language: c

sudo: required

before_install:
  - sudo apt-get update --quiet --assume-yes

before_script:
  - mkdir .deps
  - curl https://www.gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.7.6.tar.bz2 | tar xzf - -C .deps
  - pushd .deps/libgcrypt-1.7.6 && ./autogen.sh && ./configure && make && sudo make install && popd
  - git clone https://github.com/twstrike/ed448goldilocks-decaf.git .deps/decaf
  - pushd .deps/decaf && ./autogen.sh && ./configure && make && sudo make install && popd
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

script: ./autogen.sh && ./configure && make && make check
