language: c

sudo: required

before_install:
  - sudo apt-get update --quiet --assume-yes
  - sudo apt-get install haveged --only-upgrade --quiet --assume-yes # for entropy test
  - sudo service haveged start # for entropy test

before_script:
  - mkdir .deps
  - curl https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-1.26.tar.bz2 | tar xjf - -C .deps
  - pushd .deps/libgpg-error-1.26 && ./configure && make && sudo make install && popd
  - curl https://www.gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.7.6.tar.bz2 | tar xjf - -C .deps
  - pushd .deps/libgcrypt-1.7.6 && ./configure && make && sudo make install && popd
  - git clone https://github.com/twstrike/ed448goldilocks-decaf.git .deps/decaf
  - pushd .deps/decaf && ./autogen.sh && ./configure && make && sudo make install && popd
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

script:
  - ./autogen.sh && ./configure CFLAGS="-DFAST_RANDOM" && make && make check
  - ./autogen.sh && ./configure && make && make check
